# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

GEMFIRE=/home/rmay/runtime/gemfire
JAVA_HOME=/home/rmay/runtime/java
PATH=/home/rmay/bin:/home/rmay/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$GEMFIRE/bin:$JAVA_HOME/bin

export PATH
export GEMFIRE
export JAVA_HOME

echo JAVA_HOME environment variable set to $JAVA_HOME
echo GEMFIRE environment variable set to $GEMFIRE
