---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base
inputs:
  - name: repo
  #- name: tools
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - repo/gradlew build